# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4562e87962c9c8916c687b76516428047aeb87f95e723a82a2b460a441e32718550fc9c8449f4175f1fa6934e2ca4ec8c10f0717053c9faa7d0e237d15981c1b

test:
  secret_key_base: c1f484c4d983b59a96a0ce66a7aa20f3cd73ad5542b5ef0d26595b2eac669b11fca01f14cbb305a6ca1a31d3853f5a0fc3b73d2c4dad7d4c5f712c84f6dd65ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
